### ISSUE TITLE
🐛 [Bug]: 关于 toast 禁止点击背景的bug

### ISSUE THREAD

**Issue by ameegle** [3lang3/react-vant#622]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

"react-vant": "^3.1.4",

### Descripition

开启禁止点击背景
```ts
Toast.loading({ message: '匹配中...', duration: 0, position: 'top', forbidClick: true });
```
源码实现
```js
let lockCount = 0;
export function lockClick(lock) {
  if (lock) {
    if (!lockCount) {
      document.body.classList.add('rv-toast--unclickable');
    }

    lockCount += 1;
  } else if (lockCount) {
    lockCount -= 1;

    if (!lockCount) {
      document.body.classList.remove('rv-toast--unclickable');
    }
  }
}
```
```css
.rv-toast.rv-toast--unclickable {
  overflow: hidden;
  cursor: not-allowed;
}
.rv-toast.rv-toast--unclickable * {
  pointer-events: none;
}
```
